name: movies
channels:
  - conda-forge
  - defaults
dependencies:
  - abseil-cpp=20211102.0
  - aiohttp=3.9.3
  - aiosignal=1.3.1
  - alembic=1.8.1
  - annotated-types=0.6.0
  - anyio=4.3.0
  - appdirs=1.4.4
  - arrow-cpp=14.0.2
  - asn1crypto=1.5.1
  - asttokens=2.4.1
  - async-timeout=4.0.3
  - attrs=23.2.0
  - aws-c-auth=0.6.19
  - aws-c-cal=0.5.20
  - aws-c-common=0.8.5
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.15
  - aws-c-http=0.6.25
  - aws-c-io=0.13.10
  - aws-c-mqtt=0.7.13
  - aws-c-s3=0.1.51
  - aws-c-sdkutils=0.1.6
  - aws-checksums=0.1.13
  - aws-crt-cpp=0.18.16
  - aws-sdk-cpp=1.10.55
  - black=23.11.0
  - blas=1.0
  - blinker=1.6.2
  - boost-cpp=1.82.0
  - bottleneck=1.3.7
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.3.11
  - certifi=2024.2.2
  - cffi=1.16.0
  - charset-normalizer=2.0.4
  - click=8.1.7
  - cloudpickle=2.2.1
  - colorlog=5.0.1
  - comm=0.2.2
  - contourpy=1.2.0
  - cryptography=42.0.5
  - cycler=0.11.0
  - databricks-cli=0.17.6
  - dataclasses-json=0.6.4
  - debugpy=1.8.1
  - decorator=5.1.1
  - docker-py=4.4.1
  - docker-pycreds=0.4.0
  - entrypoints=0.4
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - faiss=1.7.4
  - faiss-cpu=1.7.4
  - flask=2.2.5
  - fonttools=4.25.0
  - freetype=2.12.1
  - frozenlist=1.4.1
  - gflags=2.2.2
  - gitdb=4.0.7
  - gitpython=3.1.37
  - glog=0.5.0
  - greenlet=3.0.1
  - grpc-cpp=1.48.2
  - gunicorn=20.1.0
  - icu=73.1
  - idna=3.4
  - importlib-metadata=7.0.1
  - importlib_metadata=7.0.1
  - ipykernel=6.29.3
  - ipython=8.22.2
  - isort=5.9.3
  - itsdangerous=2.0.1
  - jedi=0.19.1
  - jinja2=3.1.3
  - joblib=1.2.0
  - jpeg=9e
  - jsonpatch=1.33
  - jsonpointer=2.4
  - jupyter_client=8.6.1
  - jupyter_core=5.7.2
  - kiwisolver=1.4.4
  - krb5=1.21.2
  - langchain=0.1.13
  - langchain-community=0.0.29
  - langchain-core=0.1.35
  - langchain-text-splitters=0.0.1
  - langsmith=0.1.36
  - lcms2=2.12
  - lerc=3.0
  - libblas=3.9.0
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=8.4.0
  - libdeflate=1.17
  - libedit=3.1.20230828
  - libev=4.33
  - libevent=2.1.12
  - libfaiss=1.7.4
  - libffi=3.4.4
  - libgfortran5=11.2.0
  - liblapack=3.9.0
  - libnghttp2=1.57.0
  - libpng=1.6.39
  - libpq=16.2
  - libprotobuf=3.20.3
  - libsodium=1.0.18
  - libssh2=1.11.0
  - libthrift=0.15.0
  - libtiff=4.5.1
  - libuuid=1.41.5
  - libwebp-base=1.3.2
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - mako=1.2.3
  - markdown=3.4.1
  - markupsafe=2.1.3
  - marshmallow=3.21.1
  - matplotlib-base=3.8.0
  - matplotlib-inline=0.1.6
  - mlflow=2.9.2
  - multidict=6.0.5
  - munkres=1.1.4
  - mypy_extensions=1.0.0
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - numexpr=2.8.7
  - numpy=1.24.3
  - numpy-base=1.24.3
  - oauthlib=3.2.2
  - openjpeg=2.4.0
  - openssl=3.2.1
  - orc=1.7.4
  - orjson=3.9.15
  - packaging=23.2
  - pandas=2.2.1
  - parso=0.8.4
  - pathspec=0.10.3
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.2.0
  - pip=23.3.1
  - platformdirs=3.10.0
  - prompt-toolkit=3.0.42
  - protobuf=3.20.3
  - psutil=5.9.8
  - psycopg=3.1.18
  - psycopg-c=3.1.18
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyarrow=14.0.2
  - pycparser=2.21
  - pydantic=2.5.3
  - pydantic-core=2.14.6
  - pygments=2.17.2
  - pyjwt=2.4.0
  - pyopenssl=24.0.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.11.8
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.11
  - pytz=2023.3.post1
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - querystring_parser=1.2.4
  - re2=2022.04.01
  - readline=8.2
  - requests=2.31.0
  - s2n=1.3.27
  - scikit-learn=1.3.0
  - scipy=1.12.0
  - seaborn=0.12.2
  - setuptools=68.2.2
  - six=1.16.0
  - smmap=4.0.0
  - snappy=1.1.10
  - sniffio=1.3.1
  - sqlalchemy=2.0.25
  - sqlite=3.41.2
  - sqlparse=0.4.4
  - stack_data=0.6.2
  - tabulate=0.9.0
  - tbb=2021.8.0
  - tenacity=8.2.3
  - threadpoolctl=2.2.0
  - tk=8.6.12
  - tornado=6.4
  - traitlets=5.14.2
  - typing-extensions=4.9.0
  - typing_extensions=4.9.0
  - typing_inspect=0.9.0
  - tzdata=2024a
  - urllib3=2.1.0
  - utf8proc=2.6.1
  - wcwidth=0.2.13
  - websocket-client=0.58.0
  - werkzeug=2.3.8
  - wheel=0.41.2
  - xz=5.4.6
  - yaml=0.2.5
  - yarl=1.9.4
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - filelock==3.13.3
      - fsspec==2024.3.1
      - huggingface-hub==0.22.1
      - mpmath==1.3.0
      - networkx==3.2.1
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.4.99
      - nvidia-nvtx-cu12==12.1.105
      - psycopg2-binary==2.9.9
      - python-dotenv==1.0.1
      - regex==2023.12.25
      - safetensors==0.4.2
      - sentence-transformers==2.6.1
      - sympy==1.12
      - tokenizers==0.15.2
      - torch==2.2.2
      - tqdm==4.66.2
      - transformers==4.39.2
      - triton==2.2.0
      - libgcc-ng=13.2.0
      - mkl_random=1.2.4
      - libfaiss-avx2=1.7.4
      - intel-openmp=2023.1.0
      - keyutils=1.6.1
      - mkl-service=2.4.0
      - libgomp=13.2.0
      - _libgcc_mutex=0.1
      - mkl=2023.1.0
      - mkl_fft=1.3.8
      - ld_impl_linux-64=2.38
      - _openmp_mutex=4.5
      - libgfortran-ng=11.2.0
      - libstdcxx-ng=13.2.0
