name: movies
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - abseil-cpp=20211102.0=hd4dd3e8_0
  - aiohttp=3.9.3=py311h459d7ec_1
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - alembic=1.8.1=py311h06a4308_0
  - annotated-types=0.6.0=py311h06a4308_0
  - anyio=4.3.0=pyhd8ed1ab_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - arrow-cpp=14.0.2=h374c478_1
  - asn1crypto=1.5.1=py311h06a4308_0
  - async-timeout=4.0.3=pyhd8ed1ab_0
  - attrs=23.2.0=pyh71513ae_0
  - aws-c-auth=0.6.19=h5eee18b_0
  - aws-c-cal=0.5.20=hdbd6064_0
  - aws-c-common=0.8.5=h5eee18b_0
  - aws-c-compression=0.2.16=h5eee18b_0
  - aws-c-event-stream=0.2.15=h6a678d5_0
  - aws-c-http=0.6.25=h5eee18b_0
  - aws-c-io=0.13.10=h5eee18b_0
  - aws-c-mqtt=0.7.13=h5eee18b_0
  - aws-c-s3=0.1.51=hdbd6064_0
  - aws-c-sdkutils=0.1.6=h5eee18b_0
  - aws-checksums=0.1.13=h5eee18b_0
  - aws-crt-cpp=0.18.16=h6a678d5_0
  - aws-sdk-cpp=1.10.55=h721c034_0
  - black=23.11.0=py311h06a4308_0
  - blas=1.0=mkl
  - blinker=1.6.2=py311h06a4308_0
  - boost-cpp=1.82.0=hdb19cb5_2
  - bottleneck=1.3.7=py311hf4808d0_0
  - brotli=1.0.9=h5eee18b_7
  - brotli-bin=1.0.9=h5eee18b_7
  - brotli-python=1.0.9=py311h6a678d5_7
  - bzip2=1.0.8=h5eee18b_5
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2024.3.11=h06a4308_0
  - certifi=2024.2.2=py311h06a4308_0
  - cffi=1.16.0=py311h5eee18b_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.1.7=py311h06a4308_0
  - cloudpickle=2.2.1=py311h06a4308_0
  - colorlog=5.0.1=py311h06a4308_1
  - contourpy=1.2.0=py311hdb19cb5_0
  - cryptography=42.0.5=py311hdda0065_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - databricks-cli=0.17.6=py311h06a4308_1
  - dataclasses-json=0.6.4=pyhd8ed1ab_0
  - docker-py=4.4.1=py311h06a4308_5
  - docker-pycreds=0.4.0=pyhd3eb1b0_0
  - entrypoints=0.4=py311h06a4308_0
  - exceptiongroup=1.2.0=pyhd8ed1ab_2
  - faiss=1.7.4=py311h26a440e_0_cpu
  - faiss-cpu=1.7.4=h718b53a_0
  - flask=2.2.5=py311h06a4308_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=h4a9f257_0
  - frozenlist=1.4.1=py311h459d7ec_0
  - gflags=2.2.2=h6a678d5_1
  - gitdb=4.0.7=pyhd3eb1b0_0
  - gitpython=3.1.37=py311h06a4308_0
  - glog=0.5.0=h6a678d5_1
  - greenlet=3.0.1=py311h6a678d5_0
  - grpc-cpp=1.48.2=he1ff14a_1
  - gunicorn=20.1.0=py311h06a4308_0
  - icu=73.1=h6a678d5_0
  - idna=3.4=py311h06a4308_0
  - importlib-metadata=7.0.1=py311h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - isort=5.9.3=pyhd3eb1b0_0
  - itsdangerous=2.0.1=pyhd3eb1b0_0
  - jinja2=3.1.3=py311h06a4308_0
  - joblib=1.2.0=py311h06a4308_0
  - jpeg=9e=h5eee18b_1
  - jsonpatch=1.33=pyhd8ed1ab_0
  - jsonpointer=2.4=py311h38be061_3
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.4=py311h6a678d5_0
  - krb5=1.21.2=h659d440_0
  - langchain=0.1.13=pyhd8ed1ab_0
  - langchain-community=0.0.29=pyhd8ed1ab_0
  - langchain-core=0.1.35=pyhd8ed1ab_0
  - langchain-text-splitters=0.0.1=pyhd8ed1ab_0
  - langsmith=0.1.36=pyhd8ed1ab_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libblas=3.9.0=1_h86c2bf4_netlib
  - libboost=1.82.0=h109eef0_2
  - libbrotlicommon=1.0.9=h5eee18b_7
  - libbrotlidec=1.0.9=h5eee18b_7
  - libbrotlienc=1.0.9=h5eee18b_7
  - libcurl=8.4.0=hca28451_0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libfaiss=1.7.4=hf47d654_0_cpu
  - libfaiss-avx2=1.7.4=h1234567_0_cpu
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=13.2.0=h807b86a_5
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=13.2.0=h807b86a_5
  - liblapack=3.9.0=5_h92ddd45_netlib
  - libnghttp2=1.57.0=h2d74bed_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=16.2=h33b98f1_1
  - libprotobuf=3.20.3=he621ea3_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx-ng=13.2.0=h7e041cc_5
  - libthrift=0.15.0=h1795dd8_2
  - libtiff=4.5.1=h6a678d5_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_0
  - libzlib=1.2.13=hd590300_5
  - lz4-c=1.9.4=h6a678d5_0
  - mako=1.2.3=py311h06a4308_0
  - markdown=3.4.1=py311h06a4308_0
  - markupsafe=2.1.3=py311h5eee18b_0
  - marshmallow=3.21.1=pyhd8ed1ab_0
  - matplotlib-base=3.8.0=py311ha02d727_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py311h5eee18b_1
  - mkl_fft=1.3.8=py311h5eee18b_0
  - mkl_random=1.2.4=py311hdb19cb5_0
  - mlflow=2.9.2=py311h0389eee_0
  - multidict=6.0.5=py311h459d7ec_0
  - munkres=1.1.4=py_0
  - mypy_extensions=1.0.0=pyha770c72_0
  - ncurses=6.4=h6a678d5_0
  - numexpr=2.8.7=py311h65dcdc2_0
  - numpy=1.24.3=py311h08b1b3b_1
  - numpy-base=1.24.3=py311hf175353_1
  - oauthlib=3.2.2=py311h06a4308_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=3.2.1=hd590300_1
  - orc=1.7.4=hb3bc3d3_1
  - orjson=3.9.15=py311h46250e7_0
  - packaging=23.2=py311h06a4308_0
  - pandas=2.2.1=py311ha02d727_0
  - pathspec=0.10.3=py311h06a4308_0
  - pillow=10.2.0=py311h5eee18b_0
  - pip=23.3.1=py311h06a4308_0
  - platformdirs=3.10.0=py311h06a4308_0
  - protobuf=3.20.3=py311h6a678d5_0
  - psycopg=3.1.18=py311h0cfe25b_0
  - psycopg-c=3.1.18=py311h03dec38_0
  - pyarrow=14.0.2=py311hb6e97c4_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pydantic=2.5.3=py311h06a4308_0
  - pydantic-core=2.14.6=py311hb02cf49_0
  - pyjwt=2.4.0=py311h06a4308_0
  - pyopenssl=24.0.0=py311h06a4308_0
  - pyparsing=3.0.9=py311h06a4308_0
  - pysocks=1.7.1=py311h06a4308_0
  - python=3.11.8=h955ad1f_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.11=2_cp311
  - pytz=2023.3.post1=py311h06a4308_0
  - pyyaml=6.0.1=py311h5eee18b_0
  - querystring_parser=1.2.4=py311h06a4308_0
  - re2=2022.04.01=h295c915_0
  - readline=8.2=h5eee18b_0
  - requests=2.31.0=py311h06a4308_1
  - s2n=1.3.27=hdbd6064_0
  - scikit-learn=1.3.0=py311ha02d727_1
  - scipy=1.12.0=py311h08b1b3b_0
  - seaborn=0.12.2=py311h06a4308_0
  - setuptools=68.2.2=py311h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - smmap=4.0.0=pyhd3eb1b0_0
  - snappy=1.1.10=h6a678d5_1
  - sniffio=1.3.1=pyhd8ed1ab_0
  - sqlalchemy=2.0.25=py311h5eee18b_0
  - sqlite=3.41.2=h5eee18b_0
  - sqlparse=0.4.4=py311h06a4308_0
  - tabulate=0.9.0=py311h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tenacity=8.2.3=pyhd8ed1ab_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.12=h1ccaba5_0
  - typing-extensions=4.9.0=py311h06a4308_1
  - typing_extensions=4.9.0=py311h06a4308_1
  - typing_inspect=0.9.0=pyhd8ed1ab_0
  - tzdata=2024a=h04d1e81_0
  - urllib3=2.1.0=py311h06a4308_1
  - utf8proc=2.6.1=h5eee18b_1
  - websocket-client=0.58.0=py311h06a4308_4
  - werkzeug=2.3.8=py311h06a4308_0
  - wheel=0.41.2=py311h06a4308_0
  - xz=5.4.6=h5eee18b_0
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.9.4=py311h459d7ec_0
  - zipp=3.17.0=py311h06a4308_0
  - zlib=1.2.13=hd590300_5
  - zstd=1.5.5=hc292b87_0
  - pip:
      - filelock==3.13.3
      - fsspec==2024.3.1
      - huggingface-hub==0.22.1
      - mpmath==1.3.0
      - networkx==3.2.1
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.4.99
      - nvidia-nvtx-cu12==12.1.105
      - psycopg2-binary==2.9.9
      - python-dotenv==1.0.1
      - regex==2023.12.25
      - safetensors==0.4.2
      - sentence-transformers==2.6.1
      - sympy==1.12
      - tokenizers==0.15.2
      - torch==2.2.2
      - tqdm==4.66.2
      - transformers==4.39.2
      - triton==2.2.0
